import { Course } from "../model/course";

export const courses: Course[] = [
    {
        title: "ICQ Level 2 Early Years Practitioner",
        price: 1299,
        duration: "12 months",
        fastTrack: true,
        assessment: "Portfolio of evidence and work-based learning",
        targetAudience: "Working with babies and young children in early years settings",
        teachingMethods: "Online personal tutoring & face-to-face observation",
        fianncialOption: true,
    },
    {
        title: "ICQ Level 3 Diploma in Early Years Educators",
        price: 1399,
        duration: "12 months",
        fastTrack: true,
        assessment: "Portfolio of evidence and work-based learning",
        targetAudience: "Supporting babies and young children's learning and development",
        teachingMethods: "Online personal tutoring & face-to-face observation",
        notes: "Enrollment closes on 25th Aug",
        fianncialOption: true,
    },
    {
        title: "ICQ Level 3 Business and Management",
        price: 1499,
        duration: "12 months",
        assessment: "Portfolio of evidence and work-based learning",
        topicsLearned: "Leadership, business communication, project management",
        targetAudience: "Aspiring leaders and entrepreneurs",
        teachingMethods: "Online personal tutoring & face-to-face observation",
        spaces: "Limited Spaces Available",
        notes: "Course coming soon",
        fianncialOption: true,
    },
    {
        title: "ICQ Level 3 Certificate in Assessing Vocational Achievement (CAVA)",
        price: 669,
        duration: "9 months",
        fastTrack: true,
        assessment: "Portfolio of evidence",
        topicsLearned: "How to assess vocational learners",
        targetAudience: "Aspiring CAVA-certified Occupational Assessor",
        requirements: "Access to real learners",
        teachingMethods: "Online personal tutoring and job shadowing with a qualified early years or business assessor",
        fianncialOption: true,
    },
    {
        title: "ICQ Level 5 Diploma in Leadership for Children and Young People's Services",
        price: 2099,
        duration: "18 months",
        assessment: "Portfolio of evidence and work-based learning in the early years setting",
        targetAudience: "Early years supervisors and managers",
        requirements: "Level 3 EYE qualifications",
        teachingMethods: "Online personal tutoring & face-to-face observation",
        fianncialOption: true,
    },
    {
        title: "ICQ Level 3 Diploma for Residential Childcare",
        price: 1599,
        duration: "18 months",
        fastTrack: true,
        assessment: "Portfolio of evidence and work-based learning in the residential childcare field",
        targetAudience: "Aspiring residential childcare workers",
        teachingMethods: "Online personal tutoring & face-to-face observation",
        notes: "Course coming soon",
        fianncialOption: true,
    },
];
